CREATE TABLE brands (
  uuid VARCHAR PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE categories (
  uuid VARCHAR PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE items (
  uuid VARCHAR PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL,
  description VARCHAR NOT NULL,
  price NUMERIC NOT NULL,
  brand_id VARCHAR NOT NULL,
  category_id VARCHAR NOT NULL,
  CONSTRAINT brand_id_fkey FOREIGN KEY (brand_id)
    REFERENCES brands (uuid) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT cat_id_fkey FOREIGN KEY (category_id)
    REFERENCES categories (uuid) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE orders (
  uuid VARCHAR PRIMARY KEY,
  user_id VARCHAR UNIQUE NOT NULL,
  payment_id VARCHAR UNIQUE NOT NULL,
  items VARCHAR NOT NULL,
  total NUMERIC
);

